index:
  path: /
  controller: App\Controller\TweetController::index

ver_tweet:
  path: /tweet/{id}
  controller: App\Controller\TweetController::verTweet

# API

api_index:
  path: /api
  controller: App\Controller\ApiController::index
  methods: ["GET"]

api_get_tweet:
  path: /api/tweets/{id}
  controller: App\Controller\ApiController::getTweet
  methods: ["GET"]

api_get_user:
  path: /api/users/{id}
  controller: App\Controller\ApiController::getTweetfonyUser
  methods: ["GET"]

api_get_tweets:
  path: /api/tweets
  controller: App\Controller\ApiController::getAllTweets
  methods: ["GET"]

api_get_users:
  path: /api/users
  controller: App\Controller\ApiController::getAllTweetfonyUsers
  methods: ["GET"]

api_post_tweet:
  path: /api/tweets
  controller: App\Controller\ApiController::postTweet
  methods: ["POST"]

api_post_user:
  path: /api/users
  controller: App\Controller\ApiController::postTweetfonyUser
  methods: ["POST"]